# Generated by Django 4.2.4 on 2023-08-03 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VocabList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese', models.CharField(max_length=225)),
                ('pinyin', models.CharField(max_length=225)),
                ('english', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField()),
                ('vocablist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcard.vocablist')),
            ],
        ),
    ]
