# Generated by Django 4.2.4 on 2023-08-08 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcard', '0002_bookone_delete_card_delete_vocablist'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese', models.CharField(max_length=225)),
                ('pinyin', models.CharField(max_length=225)),
                ('english', models.CharField(max_length=225)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
