# Generated by Django 4.2.4 on 2023-08-08 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcard', '0003_customcards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcards',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customcards', to=settings.AUTH_USER_MODEL),
        ),
    ]
