# Generated by Django 4.2.4 on 2023-08-08 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0004_alter_customcards_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookOne',
            new_name='Book',
        ),
    ]
